### ==================== 環境変数 ====================
@baseUrl = http://localhost:3000
@baseUrlEcs = http://35.76.115.255:3000



### ==================== ECS環境テスト ====================
### ベース
GET {{baseUrlEcs}}

### ロギング関連
### 基本ログ
GET {{baseUrlEcs}}/api/log/basic

### エラーログ
GET {{baseUrlEcs}}/api/log/error

### 情報ログ
GET {{baseUrlEcs}}/api/log/info

### メトリクス関連
### CPU負荷テスト
GET {{baseUrlEcs}}/api/metrics/cpu-test

### メモリ負荷テスト
GET {{baseUrlEcs}}/api/metrics/memory-test

### ==================== ローカル環境テスト ====================
### ベース
GET {{baseUrl}}

### ロギング関連
### 基本ログ
GET {{baseUrl}}/api/log/basic

### エラーログ
GET {{baseUrl}}/api/log/error

### 情報ログ
GET {{baseUrl}}/api/log/info

### メトリクス関連
### CPU負荷テスト
GET {{baseUrl}}/api/metrics/cpu-test

### メモリ負荷テスト
GET {{baseUrl}}/api/metrics/memory-test